name: update github stats cache

on:
  schedule:
    - cron: "0 */24 * * *"  # a cada 24h
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Force update GitHub stats cache
        run: |
          curl -s "https://github-readme-stats.vercel.app/api?username=marcosgabrielms&show_icons=true&theme=merko&cache_seconds=0" > /dev/null
